#!/bin/bash
git -C /home/homeassistant/config/appdaemon/appdaemon_apps remote add github_rsdata_appdaemon_apps git@github.com:daverinnadesan/appdaemon_apps.git
echo "Commiting changes"
git -C /home/homeassistant/config/appdaemon/appdaemon_apps commit -a -m "Script Commit"
echo "Pushing appdaemon_apps to github Master"
git -C /home/homeassistant/config/appdaemon/appdaemon_apps push github_rsdata_appdaemon_apps master
echo "Done"
